# Generated by Django 5.1 on 2024-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_category', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Others', 'Others')], default='Personal', max_length=200)),
                ('task_category_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=200)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
